import type { Metadata } from "next";
import { Footer, Header, PageIntro, StatusDot } from "../components";

export const metadata: Metadata = { title: "Experience", description: "Manufacturing engineering, process engineering, and robotics education of Harsh Patel." };

export default function ExperiencePage() {
  return <main><Header active="experience" /><PageIntro index="02" eyebrow="EXPERIENCE LOG" title="Manufacturing insight. Software-defined robotics." copy="My background spans sensor-production workflows, pump commissioning and testing, CAD, automation improvement, and graduate robotics software." />
    <section className="timeline shell" aria-label="Professional experience">
      <article><div className="timeline-meta"><span>EXPECTED SEP 2026</span><small>PHILADELPHIA, PA</small></div><div><p className="eyebrow"><StatusDot /> GRADUATE STUDY</p><h2>M.S. Robotics and Autonomy</h2><h3>Drexel University</h3><p>Graduate work focused on mobile robot navigation, localization, SLAM, path planning, manipulation, computer vision, and controls using ROS/ROS 2, C++, Python, Gazebo, RViz, and MoveIt.</p><div className="tag-row static"><span>ROS 2</span><span>Autonomy</span><span>MoveIt</span><span>Computer Vision</span></div></div></article>
      <article><div className="timeline-meta"><span>OCT 2025 — MAR 2026</span><small>BRIDGEPORT, NJ</small></div><div><p className="eyebrow"><StatusDot /> MANUFACTURING ENGINEERING CO-OP</p><h2>Manufacturing Engineering Co-op</h2><h3>DwyerOmega Engineering</h3><p>Created and maintained SolidWorks parts, assemblies, and drawings for fit checks, manufacturability reviews, engineering changes, and tooling support. Supported automation-improvement initiatives for sensor and instrumentation production, and authored standardized work instructions and Excel-based tools that reduced lookup errors, assembly variation, and documentation inconsistencies.</p><div className="tag-row static"><span>SolidWorks</span><span>Automation Improvement</span><span>Documentation</span><span>Excel</span></div></div></article>
      <article><div className="timeline-meta"><span>DEC 2020 — AUG 2024</span><small>AHMEDABAD, INDIA</small></div><div><p className="eyebrow"><StatusDot /> SENIOR PROCESS ENGINEER</p><h2>Senior Process Engineer</h2><h3>Flowell Water Pumps</h3><p>Drove CAD-based process improvements with mechanical, electrical, QA, and production teams, contributing to a 15% manufacturing-cost reduction. Led commissioning, testing, and optimization of high-efficiency centrifugal pump assemblies and translated prototype data into reliability-focused design and process recommendations.</p><div className="tag-row static"><span>Process Engineering</span><span>CAD</span><span>Commissioning</span><span>Testing</span><span>15% Cost Reduction</span></div></div></article>
    </section>
    <section className="experience-note shell"><span className="big-number">15%</span><div><p className="eyebrow">MEASURABLE IMPACT</p><h2>I connect software decisions to production and hardware constraints.</h2><p>My process-engineering work delivered measurable manufacturing improvements, while robotics projects let me apply the same validation mindset to planning, control, perception, and autonomy.</p></div></section>
    <Footer /></main>;
}
