import type { Metadata } from "next";
import { Footer, Header, PageIntro, StatusDot } from "../components";

export const metadata: Metadata = { title: "Projects", description: "ROS 2 navigation, path planning, manipulation, computer vision, and controls projects by Harsh Patel." };

const projects = [
  { id: "sentry", index: "01", type: "ROS 2 · BEHAVIOR TREES · PERCEPTION", title: "Autonomous Patrol Robot — Behavior Trees & Marker", summary: "A ROS 2 patrol system that coordinates autonomous mission execution, battery recovery, and marker-triggered behavior transitions in simulation.", challenge: "Keep long-running patrol behavior reliable while handling low-battery recovery and reactive visual-marker responses without brittle branching logic.", solution: "Built the behavior logic in BehaviorTree.CPP v4 and added a Python OpenCV ArUco node that publishes detection state over a ROS 2 topic for mission transitions.", outcome: "The patrol stack now moves through Nav2-backed mission branches with dependable marker-driven responses and a clearer separation between perception and high-level control.", tags: ["ROS 2", "C++", "BehaviorTree.CPP v4", "Nav2", "OpenCV", "ArUco"] },
  { id: "warehouse", index: "02", type: "DYNAMIC PLANNING · GAZEBO", title: "Autonomous Warehouse Robot Path Planning", summary: "A dynamic warehouse navigation project focused on replanning when newly detected obstacles invalidate the current route.", challenge: "Maintain forward progress toward the goal even when obstacles appear after the original path has already been planned.", solution: "Implemented D* Lite for graph-based replanning in ROS/Gazebo and paired it with Artificial Potential Field methods for local obstacle avoidance.", outcome: "Validated goal-to-goal navigation across changing obstacle layouts in Gazebo and RViz, then packaged the setup with Docker for repeatable one-command use.", tags: ["D* Lite", "APF", "ROS", "Gazebo", "RViz", "Docker"] },
  { id: "manipulator", index: "03", type: "MANIPULATION · MOTION PLANNING", title: "OpenManipulator-X Manipulation & Trajectory Planning", summary: "A manipulation testbed for validating kinematics, comparing motion planners, and executing repeatable trajectories on a real robot model.", challenge: "Verify the manipulator model and choose planners using measurable performance rather than visual success alone.", solution: "Validated URDF forward kinematics and damped-least-squares inverse kinematics against MoveIt poses, then benchmarked RRTConnect, PRM, and KPIECE for planning time and tracking quality.", outcome: "Developed ROS/Python nodes for joint-space, Cartesian, waypoint, and quintic-polynomial trajectories that support repeatable experiments and motion analysis.", tags: ["OpenManipulator-X", "MoveIt", "URDF", "RRTConnect", "PRM", "KPIECE", "Python"] },
  { id: "vision", index: "04", type: "PERCEPTION · STEREO VISION", title: "Computer Vision & Stereo Calibration", summary: "An OpenCV perception pipeline for calibration, feature extraction, correspondence matching, and depth estimation from stereo imagery.", challenge: "Recover reliable scene geometry from stereo image pairs while maintaining consistent correspondences between views.", solution: "Implemented stereo calibration, Harris corner detection, edge extraction, and SIFT/FLANN matching in OpenCV to build a robust perception workflow.", outcome: "Estimated depth from calibrated image pairs and evaluated measurement accuracy against known geometry to confirm the pipeline’s reliability.", tags: ["OpenCV", "Stereo Calibration", "SIFT", "FLANN", "Harris Corners"] },
  { id: "adrc", index: "05", type: "CONTROLS · EMBEDDED SYSTEMS", title: "ADRC-Controlled Sensor System", summary: "An embedded controls project that uses disturbance-rejection logic to stabilize a real sensor-actuator platform.", challenge: "Maintain output tracking under changing disturbance conditions on a physical Arduino-based system.", solution: "Implemented C-based sensor/actuator logic with Active Disturbance Rejection Control and modeled the system in MATLAB/Simulink for comparison.", outcome: "Compared simulation and hardware performance to validate tracking stability and disturbance rejection under controlled conditions.", tags: ["ADRC", "Arduino", "C", "MATLAB", "Simulink", "Sensors"] },
  { id: "localization", index: "06", type: "LOCALIZATION · STATE ESTIMATION", title: "EKF & Monte Carlo Localization", summary: "A localization study that compares nonlinear filtering and particle-based estimation for pose tracking in noisy mobile-robot environments.", challenge: "Estimate position and orientation under noisy differential-drive motion and imperfect range-bearing observations.", solution: "Built EKF prediction and correction with analytical Jacobians and a Monte Carlo localization pipeline with motion, measurement, weighting, and resampling stages.", outcome: "Visualized corrected trajectories, covariance, particle convergence, and estimator uncertainty across simulated motion to compare filter behavior.", tags: ["EKF", "MCL", "Python", "NumPy", "ROS 2"] },
];

export default function ProjectsPage() {
  return <main><Header active="projects" /><PageIntro index="01" eyebrow="PROJECT ARCHIVE" title="Robotics systems, explained from problem to outcome." copy="Verified work across autonomous navigation, dynamic planning, manipulation, perception, localization, and embedded control." />
    <section className="project-list shell">{projects.map((p) => <article id={p.id} className="project-detail" key={p.id}><div className="project-detail-head"><span>{p.index}</span><p><StatusDot /> {p.type}</p></div><div className="project-detail-main"><h2>{p.title}</h2><p className="project-summary">{p.summary}</p><div className="detail-grid"><div><h3>Challenge</h3><p>{p.challenge}</p></div><div><h3>Approach</h3><p>{p.solution}</p></div><div><h3>Result</h3><p>{p.outcome}</p></div></div><div className="tag-row static">{p.tags.map(t => <span key={t}>{t}</span>)}</div></div></article>)}</section><Footer /></main>;
}
