import type { Metadata } from "next";
import { Footer, Header, PageIntro, StatusDot } from "../components";

export const metadata: Metadata = { title: "Projects", description: "ROS 2 navigation, path planning, manipulation, computer vision, and controls projects by Harsh Patel." };

const projects = [
  { id: "sentry", index: "01", type: "ROS 2 · BEHAVIOR TREES · PERCEPTION", title: "Autonomous Patrol Robot — Behavior Trees & Marker", summary: "A reactive C++ patrol system that connects Nav2 mission execution with battery recovery and marker-driven behaviors.", challenge: "Coordinate long-running patrol actions, low-battery recovery, and visual marker responses without turning the control flow into fragile conditional logic.", solution: "Built the patrol behavior with BehaviorTree.CPP v4 and developed a Python OpenCV ArUco node that publishes detection state on a ROS 2 topic for behavior-tree transitions.", outcome: "Patrol, battery-recovery, and marker-response branches run through Nav2 in simulation; the current milestone integrates the perception topic into the C++ tree for reactive marker-driven patrol.", tags: ["ROS 2", "C++", "BehaviorTree.CPP v4", "Nav2", "OpenCV", "ArUco"] },
  { id: "warehouse", index: "02", type: "DYNAMIC PLANNING · GAZEBO", title: "Autonomous Warehouse Robot Path Planning", summary: "A dynamic warehouse navigation system that replans when newly detected obstacles invalidate the current route.", challenge: "Maintain goal progress when obstacles appear after the original route has already been planned.", solution: "Implemented D* Lite graph search in ROS/Gazebo and applied Artificial Potential Field planning for dynamic obstacle avoidance.", outcome: "Validated goal-to-goal routes across changing obstacle layouts in Gazebo and RViz, then containerized the environment with Docker for one-command reproducibility.", tags: ["D* Lite", "APF", "ROS", "Gazebo", "RViz", "Docker"] },
  { id: "manipulator", index: "03", type: "MANIPULATION · MOTION PLANNING", title: "OpenManipulator-X Manipulation & Trajectory Planning", summary: "A manipulation testbed for validating robot kinematics, comparing motion planners, and executing repeatable trajectories.", challenge: "Verify the manipulator model and choose planners using measurable performance rather than visual success alone.", solution: "Validated URDF forward kinematics and damped-least-squares IK against MoveIt poses; benchmarked RRTConnect, PRM, and KPIECE by planning time, pose error, and tracking error.", outcome: "Developed ROS/Python nodes for joint-space, Cartesian, waypoint, and quintic-polynomial trajectories, enabling repeatable motion experiments.", tags: ["OpenManipulator-X", "MoveIt", "URDF", "RRTConnect", "PRM", "KPIECE", "Python"] },
  { id: "vision", index: "04", type: "PERCEPTION · STEREO VISION", title: "Computer Vision & Stereo Calibration", summary: "An OpenCV perception pipeline for calibration, feature extraction, correspondence matching, and depth estimation.", challenge: "Recover useful scene geometry from stereo imagery while maintaining reliable correspondences between views.", solution: "Implemented stereo calibration, Harris corners, edge detection, and SIFT/FLANN feature matching in OpenCV.", outcome: "Estimated depth from calibrated stereo pairs and evaluated measurement accuracy against known image geometry.", tags: ["OpenCV", "Stereo Calibration", "SIFT", "FLANN", "Harris Corners"] },
  { id: "adrc", index: "05", type: "CONTROLS · EMBEDDED SYSTEMS", title: "ADRC-Controlled Sensor System", summary: "A disturbance-rejection controller deployed on a physical Arduino LED-photoresistor platform.", challenge: "Maintain output tracking when the sensor-actuator system experiences changing disturbance conditions.", solution: "Implemented C-based sensor and actuator logic with Active Disturbance Rejection Control, then modeled the system in MATLAB/Simulink.", outcome: "Compared tracking stability and disturbance rejection in simulation and on the embedded platform under controlled disturbances.", tags: ["ADRC", "Arduino", "C", "MATLAB", "Simulink", "Sensors"] },
  { id: "localization", index: "06", type: "LOCALIZATION · STATE ESTIMATION", title: "EKF & Monte Carlo Localization", summary: "Mobile-robot localization studies using nonlinear filtering and particle-based Bayesian estimation.", challenge: "Estimate pose under noisy differential-drive motion and imperfect range-bearing observations.", solution: "Built EKF prediction/correction with analytical Jacobians and MCL motion, measurement, weighting, and resampling stages.", outcome: "Visualized corrected trajectories, covariance, particle convergence, and estimator uncertainty across simulated motion.", tags: ["EKF", "MCL", "Python", "NumPy", "ROS 2"] },
];

export default function ProjectsPage() {
  return <main><Header active="projects" /><PageIntro index="01" eyebrow="PROJECT ARCHIVE" title="Robotics systems, explained from problem to outcome." copy="Verified work across autonomous navigation, dynamic planning, manipulation, perception, localization, and embedded control." />
    <section className="project-list shell">{projects.map((p) => <article id={p.id} className="project-detail" key={p.id}><div className="project-detail-head"><span>{p.index}</span><p><StatusDot /> {p.type}</p></div><div className="project-detail-main"><h2>{p.title}</h2><p className="project-summary">{p.summary}</p><div className="detail-grid"><div><h3>Challenge</h3><p>{p.challenge}</p></div><div><h3>Approach</h3><p>{p.solution}</p></div><div><h3>Result</h3><p>{p.outcome}</p></div></div><div className="tag-row static">{p.tags.map(t => <span key={t}>{t}</span>)}</div></div></article>)}</section><Footer /></main>;
}
