import type { Metadata } from "next";
import { Footer, Header, PageIntro } from "../components";
import PrintButton from "./print-button";

export const metadata: Metadata = { title: "Résumé", description: "Résumé of Harsh Patel, Robotics & Autonomy M.S. candidate targeting robotics software and autonomy roles." };

export default function ResumePage() {
  return <main><Header active="resume" /><PageIntro index="04" eyebrow="RÉSUMÉ" title="Robotics software, autonomy, and hardware-aware engineering." copy="This page reflects my current résumé. Download the original PDF or use the print version below." />
    <section className="resume-actions shell no-print"><a className="button button-primary" href="/Harsh_Patel_Resume.pdf" download>Download résumé PDF <span>↓</span></a><PrintButton /><a className="button button-quiet" href="mailto:harsh8121998@gmail.com">Email me</a></section>
    <article className="resume-sheet shell">
      <header><div><h1>Harsh Patel</h1><p>Robotics Software &amp; Autonomy</p></div><div><a href="mailto:harsh8121998@gmail.com">harsh8121998@gmail.com</a><a href="tel:+14452089961">+1 (445) 208-9961</a><a href="https://www.linkedin.com/in/harshpatel0812/">linkedin.com/in/harshpatel0812</a><a href="https://github.com/Harshpatel0812">github.com/Harshpatel0812</a></div></header>
      <section><h2>Summary</h2><p>Robotics &amp; Autonomy M.S. candidate targeting entry-level Robotics Software and Autonomy roles, with hands-on experience building ROS/ROS 2, C++, and Python systems for mobile robot navigation, localization, SLAM, path planning, and manipulation. Built and validated TurtleBot3, OpenManipulator-X, EKF/MCL, A*/D* Lite, MoveIt, and Gazebo/RViz projects across simulation and hardware, backed by manufacturing and process-engineering experience.</p></section>
      <section><h2>Education</h2><div className="resume-items"><div className="resume-row"><div><h3>Drexel University</h3><p>M.S. Robotics and Autonomy</p></div><span>Philadelphia, PA · Expected Sep 2026</span></div><div className="resume-row"><div><h3>Gujarat Technological University</h3><p>B.E. Mechanical Engineering</p></div><span>Ahmedabad, India · Jul 2016-Aug 2020</span></div></div></section>
      <section><h2>Experience</h2><div className="resume-items"><div className="resume-row"><div><h3>Manufacturing Engineering Co-op</h3><p>DwyerOmega Engineering</p></div><span>Bridgeport, NJ · Oct 2025-Mar 2026</span></div><ul><li>Created SolidWorks parts, assemblies, and drawings for fit checks, manufacturability reviews, engineering changes, and tooling support.</li><li>Supported automation-improvement initiatives for sensor and instrumentation production workflows.</li><li>Authored standardized work instructions, engineering documentation, and Excel tools to reduce lookup errors and assembly variation.</li></ul><div className="resume-row"><div><h3>Senior Process Engineer</h3><p>Flowell Water Pumps</p></div><span>Ahmedabad, India · Dec 2020-Aug 2024</span></div><ul><li>Drove cross-functional CAD-based process improvements that contributed to a 15% manufacturing-cost reduction.</li><li>Led commissioning, testing, and optimization of high-efficiency centrifugal pump assemblies.</li><li>Translated prototype test data into design and process recommendations that improved reliability.</li></ul></div></section>
      <section><h2>Technical Skills</h2><div className="resume-skills"><p><strong>Programming &amp; ROS:</strong> Python, C++, C, MATLAB, Bash, ROS 2, ROS Noetic, TF/TF2, MoveIt, URDF, rosbag</p><p><strong>Planning &amp; Control:</strong> A*, D* Lite, RRTConnect, PRM, KPIECE, trajectory generation, Jacobian IK, PID, ADRC</p><p><strong>Perception &amp; Vision:</strong> OpenCV, stereo calibration, SIFT/FLANN, Harris corners, edge detection</p><p><strong>Hardware &amp; CAD:</strong> Arduino, TurtleBot3, OpenManipulator-X, sensor integration, Mitsubishi GX Works2 PLC, SolidWorks</p></div></section>
      <section><h2>Selected Projects</h2><div className="resume-items"><div><h3>Autonomous Patrol Robot — Behavior Trees &amp; Marker</h3><small>C++ · BehaviorTree.CPP v4 · Nav2 · OpenCV ArUco</small><ul><li>Built patrol, battery-recovery, and marker-response branches and a ROS 2 perception topic for reactive behavior transitions.</li></ul></div><div><h3>Autonomous Warehouse Robot Path Planning</h3><small>D* Lite · APF · Gazebo · RViz · Docker</small><ul><li>Enabled obstacle-aware replanning across changing warehouse layouts and packaged the environment for one-command setup.</li></ul></div><div><h3>OpenManipulator-X Manipulation &amp; Trajectory Planning</h3><small>MoveIt · URDF · RRTConnect · PRM · KPIECE</small><ul><li>Validated kinematics, benchmarked planners, and built ROS/Python trajectory-execution nodes.</li></ul></div><div><h3>Computer Vision &amp; Stereo Calibration</h3><small>OpenCV · SIFT/FLANN · Harris Corners</small><ul><li>Calibrated stereo imagery, matched features, and estimated scene depth against known geometry.</li></ul></div><div><h3>ADRC-Controlled Sensor System</h3><small>Arduino · C · MATLAB/Simulink</small><ul><li>Deployed and validated disturbance-rejection control on an LED-photoresistor platform.</li></ul></div></div></section>
      <section><h2>Certifications</h2><p>ROS 2 &amp; ROS (Noetic/Melodic/Kinetic) · MATLAB &amp; Simulink Onramp (MathWorks) · Mitsubishi GX Works2 PLC (Udemy)</p></section>
    </article><Footer /></main>;
}
